# Generated by Django 2.2.3 on 2019-07-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsmanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
