# Generated by Django 2.2.3 on 2019-07-08 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsmanage', '0002_auto_20190708_1017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtendedUser',
        ),
    ]
