# Generated by Django 2.2.3 on 2019-07-08 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lsmanage', '0003_delete_extendeduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('call_no', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('auther', models.CharField(blank=True, max_length=30, null=True)),
                ('publisher', models.CharField(blank=True, max_length=50, null=True)),
                ('Quantity', models.IntegerField(default=0)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
