# Generated by Django 2.2.3 on 2019-07-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsmanage', '0004_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user_id',
            new_name='user',
        ),
    ]
