# Generated by Django 2.2.3 on 2019-07-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsmanage', '0005_auto_20190708_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Quantity',
            new_name='issued',
        ),
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
