# Generated by Django 2.2.3 on 2019-07-08 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsmanage', '0007_auto_20190708_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='auther',
            new_name='author',
        ),
    ]
