# Generated by Django 2.2.3 on 2019-07-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lsmanage', '0008_auto_20190708_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='call_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
