# Generated by Django 2.2.3 on 2019-07-09 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lsmanage', '0009_auto_20190708_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='IssueBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('student_name', models.CharField(blank=True, max_length=30, null=True)),
                ('student_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lsmanage.Book')),
            ],
        ),
    ]
