# Generated by Django 2.2.3 on 2019-07-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lsmanage', '0010_auto_20190709_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuebook',
            old_name='book_id',
            new_name='book',
        ),
    ]
